### ISSUE TITLE
PPC instruction stwu not parsing: maybe related to negative numbers

### ISSUE THREAD

**Issue by fraser125** [matt-kempster/m2c#241]
Originally found using decomp.me but reproduced at https://simonsoftware.se/other/m2c.html
Code line
```ppc
/* 803FA8CC  94 21 FF F0 */	stwu r1, -0x10(r1)
```
Decompilation failure:
Failed to parse instruction at stdin line 3: stwu r1, -0x10(r1)

```
Error: operand out of range (0x000000000000ffff is not between 0xffffffffffff8000 and 0x00000000000007fff)
```

![image](https://user-images.githubusercontent.com/1725115/179581292-40640bfc-6c4c-463c-88dc-0364b74dff6d.png)

**Comment by simonlindholm** [comment]
I can't reproduce this error. If I put just `/* 803FA8CC  94 21 FF F0 */	stwu r1, -0x10(r1)` in the textarea at https://simonsoftware.se/other/m2c.html and set target arch to PPC I get a successful decompile.

**Comment by fraser125** [comment]
I didn't set the target (I forgot) so it works now for me on m2c, I'll see what I can find out about how decomp.me is doing their side. Thanks!
