### ISSUE TITLE
[Bug] Does Absolutely Nothing

### ISSUE THREAD

**Issue by NickDeBeenSAE** [matt-kempster/m2c#262]
As the title suggests, the file does absolutely nothing.

I used the following command, which produced no file, therefore no output:

``python3 m2c.py -t ppc-mwcc-c /home/nickdebeen/Desktop/USR_DATA > USR_DATA_Converted.c``

**Comment by NickDeBeenSAE** [comment]
Raw Binary, MIPS32 PowerPC code.

It a PS3 (PlayStation 3) save file.

I am trying to modify it.

**Comment by mkst** [comment]
That is not how this tool works. You need to feed assembly code (i.e. something like objdump -d output)

**Comment by ethteck** [comment]
You're mistaken. Save files don't have machine code (assembly) in them. It's just data like mkst said

**Comment by simonlindholm** [comment]
Yeah, m2c requires textual assembly as input.

**Comment by NickDeBeenSAE** [comment]
> You're mistaken. Save files don't have machine code (assembly) in them. It's just data like mkst said

I am not mistaken because Ghidra for the win.

I set its disassembly language to be MIPS32 and there you go, it shows disassembled MIPS32 machine code.
