### ISSUE TITLE
lwl/lwr error

### ISSUE THREAD

**Issue by mkst** [matt-kempster/m2c#285]
https://decomp.me/scratch/UVAkx

On mobile, will write more when I'm on pc but wanted to create an issue so this is not forgotten

**Comment by simonlindholm** [comment]
The error here is partly on decomp.me's side: it should be passing a little-endian platform at https://github.com/decompme/decomp.me/blob/a5249f922c67a004c8e7b4c05a4ef5d8b4dd2855/backend/coreapp/m2c_wrapper.py#L20

Though it looks like there is a m2c bug here where all addresses are off by 3.

**Comment by mkst** [comment]
Nice find, I'll look at correcting that decomp.me issue!

**Comment by simonlindholm** [comment]
Fixed the off-by-3!
